using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using UnityEngine;

namespace Nanite
{
    /// <summary>
    /// 与 meshoptimizer 中 <c>meshopt_Meshlet</c> 内存布局一致（4×uint32）。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct Meshlet
    {
        public uint vertex_offset;
        public uint triangle_offset;
        public uint vertex_count;
        public uint triangle_count;
    }

    /// <summary>
    /// 簇在屏幕/视角下的包围球与几何误差（后续 Build DAG / LOD 会用到）。
    /// </summary>
    [Serializable]
    public struct LODBounds
    {
        public Vector3 center;
        public float radius;
        public float error;
    }

    /// <summary>
    /// 合并/简化后的一组子 Cluster，构成 DAG 中的一个节点（Cluster Group）。
    /// </summary>
    [Serializable]
    public class ClusterGroup
    {
        /// <summary>本组包含的叶子/子 Cluster 在 <see cref="NaniteSubMesh.clusterList"/> 中的索引。</summary>
        public List<int> children = new List<int>();
        /// <summary>
        /// Coarser clusters generated by simplifying <see cref="children"/>. The pair
        /// children -&gt; parents is the persistent refinement edge used by runtime Page
        /// traversal. Terminal/root groups intentionally leave this list empty.
        /// </summary>
        public List<int> parents = new List<int>();
        public Vector3 boundsCenter;
        public float radius;
        public float minLodError;
        public float maxParentLodError;
        public int mipLevel;
        /// <summary>
        /// The replacement was produced by the terminal vertex-update path. Its
        /// UV contract uses the same robust 99.5 percentile gate as the builder,
        /// while ordinary producers retain the conservative maximum-edge gate.
        /// </summary>
        public bool usesRobustUvGate;
        /// <summary>
        /// This group starts a permanently resident hierarchy branch. Root residency is
        /// independent from maxParentLodError: a pruned component can remain discoverable
        /// in the root set while using a finite error to disappear below one pixel.
        /// </summary>
        public bool isRootSet;
    }

    /// <summary>离线 Nanite 构建结果：全部 Cluster + 各级 Cluster Group + 最大 Mip。</summary>
    [Serializable]
    public class NaniteSubMesh
    {
        public List<ClusterGroup> clusterGroupList = new List<ClusterGroup>();
        public List<Cluster> clusterList = new List<Cluster>();
        public int maxMipLevel;
    }

    /// <summary>
    /// 单个 Cluster：引用原始网格顶点索引的三角形列表，以及自身/父级边界信息。
    /// </summary>
    [Serializable]
    public class Cluster
    {
        public int mip;
        public int[] indices = Array.Empty<int>();
        // Geometry bounds are intentionally independent from the group LOD spheres.
        // A generated cluster shares its LOD error sphere with siblings, but frustum,
        // HZB, shadow and raster admission must use the much tighter meshlet bounds.
        public LODBounds geometry;
        // Object-space longest triangle edge. Raster binning projects this value
        // directly instead of treating the complete cluster bound as one triangle.
        public float longestEdge;
        // meshoptimizer cone_axis_s8.xyz + cone_cutoff_s8 packed little-endian.
        public uint packedCone;
        public LODBounds self;
        public LODBounds parent;
    }

    /// <summary>
    /// Mutable geometry arena shared by every sub-mesh during one bake. LOD0 keeps
    /// the imported vertex IDs; coarse hierarchy levels append their optimized
    /// position/attribute payload and therefore no longer have to approximate an
    /// aggressive simplification using only the immutable source vertices.
    /// </summary>
    public sealed class NaniteBuildGeometry
    {
        public readonly List<Vector3> positions;
        public readonly List<Vector3> normals;
        public readonly List<Vector2> uvs;
        public readonly List<Vector4> tangents;

        public NaniteBuildGeometry(
            Vector3[] sourcePositions,
            Vector3[] sourceNormals,
            Vector2[] sourceUvs,
            Vector4[] sourceTangents)
        {
            if (sourcePositions == null)
                throw new ArgumentNullException(nameof(sourcePositions));

            int count = sourcePositions.Length;
            positions = new List<Vector3>(sourcePositions);
            normals = new List<Vector3>(count);
            uvs = new List<Vector2>(count);
            tangents = new List<Vector4>(count);
            bool hasNormals = sourceNormals != null && sourceNormals.Length == count;
            bool hasUvs = sourceUvs != null && sourceUvs.Length == count;
            bool hasTangents = sourceTangents != null && sourceTangents.Length == count;
            for (int vertexIndex = 0; vertexIndex < count; vertexIndex++)
            {
                normals.Add(hasNormals ? sourceNormals[vertexIndex] : Vector3.up);
                uvs.Add(hasUvs ? sourceUvs[vertexIndex] : Vector2.zero);
                tangents.Add(hasTangents
                    ? sourceTangents[vertexIndex]
                    : new Vector4(1f, 0f, 0f, 1f));
            }
        }

        public int Count => positions.Count;

        public void Append(Vector3 position, Vector3 normal, Vector2 uv, Vector4 tangent)
        {
            positions.Add(position);
            normals.Add(normal);
            uvs.Add(uv);
            tangents.Add(tangent);
        }

        public void Truncate(int count)
        {
            if (count < 0 || count > Count)
                throw new ArgumentOutOfRangeException(nameof(count));
            int removeCount = Count - count;
            if (removeCount == 0)
                return;
            positions.RemoveRange(count, removeCount);
            normals.RemoveRange(count, removeCount);
            uvs.RemoveRange(count, removeCount);
            tangents.RemoveRange(count, removeCount);
        }
    }
}
